# -*- coding: utf-8 -*-
"""vector_database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zS9hD6jJOvkwPJpewH0iIPzJAE_v0tSJ
"""

import sqlite3


conn = sqlite3.connect(":memory:")

cursor = conn.cursor()


cursor.execute("""
    CREATE TABLE predictions (
        id INTEGER PRIMARY KEY,
        model_name TEXT,
        input_text TEXT,
        confidence REAL
    )
""")


cursor.execute("""
    INSERT INTO predictions (model_name, input_text, confidence)
    VALUES ('gpt-4', 'classify this email', 0.97)
""")

data = [
    ('yolo-v8', 'detect objects in image', 0.88),
    ('bert', 'classify this email', 0.76),
    ('gpt-4', 'summarize this document', 0.95),
]

cursor.executemany("""
    INSERT INTO predictions (model_name, input_text, confidence)
    VALUES (?, ?, ?)
""", data)

cursor.execute("""
    SELECT model_name, confidence
    FROM predictions
    WHERE confidence > 0.90
""")

cursor.execute("""
    SELECT model_name, AVG(confidence), COUNT(*)
    FROM predictions
    GROUP BY model_name
""")



cursor.execute("""
    SELECT model_name, AVG(confidence) AS avg_confidence, COUNT(*) AS total_runs
    FROM predictions
    GROUP BY model_name
    ORDER BY avg_confidence DESC
""")

cursor.execute("""
  select *
  from predictions
  WHERE model_name = 'gpt-4'
  ORDER BY confidence DESC
  LIMIT 1
""")

print(cursor.fetchall())

pip install chromadb
pip install langchain --upgrade chromadb langchain-community
pip install pypdf
pip install langchain-groq
pip install langchain-openai
pip install sentence-transformers langchain-huggingface

import chromadb

client = chromadb.Client()

collection = client.create_collection("ai_documents")

collection.add(
    documents=[
        "how to fix a leaking pipe",
        "repairing a broken water tube",
        "machine learning model training guide",
        "neural networks and deep learning",
        "cooking pasta with tomato sauce"
    ],
    ids=["doc1", "doc2", "doc3", "doc4", "doc5"]
)

results = collection.query(
    query_texts=["broken pipe repair"],
    n_results=2
)
print(results['documents'])

all_data = collection.get(include=["embeddings"])
print(len(all_data["embeddings"][0]))

"""**RAG**"""

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/CV of B.Sc. Eng. Nafiz Khan.pdf")

pages = loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 250, chunk_overlap = 50)

chunks = text_splitter.split_documents(pages)

print(len(chunks))
print(chunks[0])

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name ="all-MiniLM-L6-v2")

vector_store = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    persist_directory="chroma_db"
)

retriever = vector_store.as_retriever(search_kwargs={"k": 2})
result = retriever.invoke("give me his email")

for res in result:
  print(res.page_content)
  print("End of chunk\n")

import os

os.environ["GROQ_API_KEY"] = "your_api_key"

from langchain_groq import ChatGroq

llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.3)

from langchain_core.prompts import ChatPromptTemplate
 from langchain_core.runnables import RunnablePassthrough

prompt = ChatPromptTemplate.from_template("""
Answer the question based only on the context below.

Context: {context}

Question: {question}
""")

chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
)

response = chain.invoke("I am thinking of testing his ability, like a take home project of 3 days")

print(response.content)

